//=========================================================
// src/lab4_timer2_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB52_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$
sbit led = P1^3;
//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void
SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

void
disable_watchdog(){
  WDTCN = 0xAD;
  WDTCN = 0xDE;
}
void crossbar_enable(){
  XBR2 = XBR2_XBARE__ENABLED;
  P1MDIN = P1MDIN_B3__DIGITAL;
  P1MDOUT = P1MDOUT_B3__PUSH_PULL;
}

void clock_select(){
  CLKSEL = CLKSEL_CLKSL__HFOSC0_clk24p5 | CLKSEL_CLKDIV__SYSCLK_DIV_8; // clksel= 30625000
  TMR2CN0 |= TMR2CN0_T2XCLK__SYSCLK_DIV_12;  // timer2 clock control = 30625000/12 = 255208
}

SI_INTERRUPT(TIMER2_ISR, TIMER2_IRQn){
  TMR2CN0_TF2H = 0;  // clear the flag
  led = ~led; // Toggle the led
}
// Generate a 10Hz
void timer2_16bit(){
  IE_EA = 1;  // Enable Global Interrupt
  IE_ET2 = 1; // Enable timer2 Interrupt

  // F_timer2 = (F_timer2_clock_control/(2^16 - TMR2RLH:TMR2RLL))=> TMR2RLH:TMR2RLL= 65536 - (F_timer2_clock_control/F_timer2)
  // TMR2RLH:TMR2RLL = 65536 - (255208/10) = 40015 = 0x9C4F
  TMR2RLL = 0x4F; // timer 2 reload low byte
  TMR2RLH = 0x9C; // timer 2 reload high byte
  TMR2CN0_TR2 = 1; // start the timer2

}
//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int
main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET ();
  disable_watchdog();
  crossbar_enable();
  clock_select();
  timer2_16bit();
  while (1)
    {
// $[Generated Run-time code]
// [Generated Run-time code]$
    }
}
