//=========================================================
// src/lab2_button_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB52_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

sbit led = P0^4;
sbit button = P0^3;
//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void
SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

void disable_watchdog(){
  WDTCN = 0xDE;
  WDTCN = 0XAD;
}

void enable_interrupt(){
  IE_EA = 1;
  IE_EX0 = 1;

}
void detect_rising_edge(){
  TCON_IT0 = 1;
  IT01CF |= IT01CF_IN0PL__ACTIVE_HIGH | IT01CF_IN0SL__P0_3;
}

void detect_falling_edge(){
  TCON_IT0 = 1;
  IT01CF |= IT01CF_IN0SL__P0_3;
}
SI_INTERRUPT(INT0_ISR, INT0_IRQn){
   led = ~led;
}
//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int
main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET ();
  disable_watchdog();
  XBR2 |= XBR2_XBARE__ENABLED;
  P0MDIN |= P0MDIN_B3__DIGITAL | P0MDIN_B4__DIGITAL;
  P0MDOUT |= P0MDOUT_B4__PUSH_PULL;

  enable_interrupt();
  detect_rising_edge();
  while (1)
    {
// $[Generated Run-time code]
// [Generated Run-time code]$
    }
}
