//=========================================================
// src/hello_8051_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB52_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
#include "retargetserial.h"
// $[Generated Includes]
// [Generated Includes]$

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void
SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}
void delay(){
  uint32_t i;
  for (i=1; i<=50000;i++){

  }
}
//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int
main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET ();
  SCON0_TI = 1;

  RETARGET_PRINTF("Hello 8051\n");
  XBR2 |= XBR2_XBARE__ENABLED;
  P1MDIN |= P1MDIN_B0__DIGITAL;
  P1MDOUT |= P1MDOUT_B0__PUSH_PULL;
  while (1)
    {
      P1_B0 = 1;
      delay();
      P1_B0 = 0;
      delay();
// $[Generated Run-time code]
// [Generated Run-time code]$
    }
}
